name: TaikoTFights
version: '${project.version}'
main: fr.salers.teamfight.TeamFightPlugin
authors: [ SalersFR ]
depend:
  - Parties
commands:
  teamfight:
    aliases:
      - teamfight
      - tfight
  setspawn:

